### ISSUE TITLE
Apps stucks on splash screen in iOS after debugging

### ISSUE THREAD

**Issue by priyanshupatra02** [Shreemanarjun/river_bricks#4]
Here is the demo :

https://github.com/Shreemanarjun/river_bricks/assets/85840449/2e81c3b9-d14a-47b0-882f-06669f1b2cf0

Whenever creating a new project and debugging it on iOS, the after keeps looping on the splash screen and doesn't move further -
Link to the issue - https://github.com/Shreemanarjun/river_bricks/blob/master/bricks/riverpod_simple_architecture/__brick__/lib/features/splash/controller/box_encryption_key_pod.dart

![WhatsApp Image 2024-05-19 at 1 08 40 PM](https://github.com/Shreemanarjun/river_bricks/assets/85840449/5a76a9e9-e90c-48d3-8534-3d2419c390a4)

**Comment by Shreemanarjun** [comment]
Working on it. Will fix it soon. Thanks for reporting the issue.

**Comment by Shreemanarjun** [comment]
Got the fix. Just change the line no 13.
 or you can update the template.

**changelog** 

v2.0.10+10


Fix IOS loading splash due to keychain access
Fix themed segment button(remove MaterialStatePropertyAll with WidgetStatePropertyAll) (Flutter 3.22)



```dart
 iOptions: IOSOptions(
      accessibility: KeychainAccessibility.unlocked,
    ),

```
